format = """
[](#1B1E26)\
$username\
[](bg:#262A34 fg:#1B1E26)\
$directory\
[](fg:#262A34 bg:#303643)\
$git_branch\
$git_status\
[](fg:#303643 bg:#3B4252)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#3B4252 bg:#464e61)\
$docker_context\
$aws\
[](fg:#464e61 bg:#5B667A)\
$time\
[ ](fg:#5B667A)\
\n $character"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#1B1E26"
style_root = "bg:#1B1E26"
format = '[$user ]($style)'

[directory]
style = "bg:#262A34"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[aws]
symbol = ""
style = "bg:#464e61"
format = '[[ $symbol $context ](bg:#464e61)]($style)'

[c]
symbol = " "
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[docker_context]
symbol = " "
style = "bg:#464e61"
format = '[[ $symbol $context ](bg:#464e61)]($style) $path'

[elixir]
symbol = " "
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[elm]
symbol = " "
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[git_branch]
symbol = ""
style = "bg:#303643"
format = '[[ $symbol $branch ](bg:#303643)]($style)'

[git_status]
style = "bg:#303643"
format = '[[($all_status$ahead_behind )](bg:#303643)]($style)'

[golang]
symbol = " "
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[haskell]
symbol = " "
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[java]
symbol = " "
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[julia]
symbol = " "
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[nodejs]
symbol = ""
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[nim]
symbol = " "
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[rust]
symbol = ""
style = "bg:#3B4252"
format = '[[ $symbol ($version) ](bg:#3B4252)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5B667A"
format = '[[ ♥ $time ](bg:#5B667A)]($style)'
